In [1]:
# Import the requests library and API key
import pandas as pd
import requests
from config import tmdb_api_key

In [2]:
# Starting URL for TMDB API including the API key from config.py
url = "https://api.themoviedb.org/3/discover/movie?api_key=" + tmdb_api_key

In [3]:
# URL for movies tagged with keywords "LGBT, gay, lesbian, trans, and transgender"
# and using the language (English), region (US), release date start (01-01-2000) and end (12-31-2022), 
# sort by (release date descending) parameters. Not included are the "page" and "certification" parameters which
# will be included below.
lgbt_url = url + "&language=en-US&region=US&sort_by=primary_release_date.desc&certification_country=US&include_adult=false&include_video=false&primary_release_date.gte=2000-01-01&primary_release_date.lte=2022-12-31&with_keywords=158718%7C264384%7C264386%7C273637%7C290527%7C163037&with_original_language=en"

In [4]:
# Create a function to iterate through multiple pages of the API call. 
# Specifying the params for params with a dictionary containing the key/value pair for "page".

def get_page(page_num):
    lgbt_movies = requests.get(
        lgbt_url,
        params={"page": page_num}
    )
    # Create a variable to hold the JSON text of the 'get' request
    lgbt_movies_data = lgbt_movies.json()
    # Create a Pandas Dataframe for 'results' from the JSON dictionary
    return pd.DataFrame(lgbt_movies_data['results'])

# The number of pages you want
pages_requested = 65

# Get all pages as dataframes by calling the function "get_page()" where "page_num" is variable n + 1.
# The list comprehension will iterate through the range of "pages_requested" which is 65, adding 1 to
# each iteration to make the count 1-65.
pages = [get_page(n + 1) for n in range(pages_requested)]

# Combine pages to single dataframe using the concat function (aka concatenate)
lgbt_movies_df = pd.concat(pages)

In [5]:
# In a similar fashion to the above, create a function to iterate through multiple pages of the API call
# and to constrain the search to particular certification ratings. Specifying the params for params
# with a dictionary containing the key/value pair for "page" and "certification".

def get_ratings(page_num, rating):
    lgbt_movies = requests.get(
        lgbt_url,
        params={
            "page": page_num,
            "certification": rating}
    )
    # Create a variable to hold the JSON text of the 'get' request
    lgbt_ratings_data = lgbt_movies.json()
    # Create a Pandas Dataframe for 'results' from the JSON dictionary
    return pd.DataFrame(lgbt_ratings_data['results'])

# The number of pages you want. (Note: the max number of pages for the ratings comes from "NR" 
# having a max of 12 pages of results, and the largest amount of pages, which is why the variable
# was changed from above).
pages_requested = 12

# Get all pages for each US rating as dataframes by calling the function "get_ratings()" 
# where "page_num" is variable n + 1. The list comprehension will iterate through the range 
# of "pages_requested" which is 12, adding 1 to each iteration to make the count 1-12. The get_ratings function
# uses the second variable to specify the rating needed in the URL parameter.
pages_nr = [get_ratings(n + 1, "NR") for n in range(pages_requested)]
pages_g = [get_ratings(n + 1, "G") for n in range(pages_requested)]
pages_pg = [get_ratings(n + 1, "PG") for n in range(pages_requested)]
pages_pg13 = [get_ratings(n + 1, "PG-13") for n in range(pages_requested)]
pages_r = [get_ratings(n + 1, "R") for n in range(pages_requested)]
pages_nc17 = [get_ratings(n + 1, "NC-17") for n in range(pages_requested)]

# Combine pages for each rating to single dataframe using the concat function (aka concatenate)
lgbt_nr_df = pd.concat(pages_nr)
lgbt_g_df = pd.concat(pages_g) 
lgbt_pg_df = pd.concat(pages_pg)
lgbt_pg13_df = pd.concat(pages_pg13)
lgbt_r_df = pd.concat(pages_r)
lgbt_nc17_df = pd.concat(pages_nc17)

In [6]:
# Verify that the lgbt_movies_df was created correctly with all the necessary results.
print(len(lgbt_movies_df))
lgbt_movies_df.head()

1297

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,None,"[35, 18]",507903,en,Spoiler Alert,The story of Michael Ausiello and Kit Cowan's ...,3.317,/np3y8wm2K7YK5RT6e68hw6IzhBw.jpg,2022-12-31,Spoiler Alert,False,0.0,0
1,False,None,"[27, 53]",876802,en,Saint Drogo,Saint Drogo is a supernatural slowburn themati...,1.810,/ghq9XVBvmlbqrsKA7KDMsYOPjAu.jpg,2022-10-01,Saint Drogo,False,0.0,0
2,False,None,[10749],929477,en,Heart Shot,Teenagers Nikki and Sam are in love and planni...,2.474,None,2022-02-17,Heart Shot,False,0.0,0
3,False,/qQFvUg92Uh1jRXCNgqo9LduBDFD.jpg,[18],920345,en,EMPATHY (Or: The Girl with The Pearled Hair),After running away from her emotionally abusiv...,10.080,/59C1l5dqtKuKuKy5qlE23PV4yC6.jpg,2022-01-25,EMPATHY (Or: The Girl with The Pearled Hair),False,0.0,0
4,False,/rzu9BVI9HqY5rG0Xq05ZhewdkYP.jpg,"[18, 35]",641934,en,Am I Ok?,Lucy and Jane have been best friends for most ...,15.079,None,2022-01-24,Am I Ok?,False,8.3,2

In [7]:
# Verify that the lgbt_r_df was created correctly with all the necessary results. (This will ensure all other
# ratings dataframes were created correctly as well).
print(len(lgbt_r_df))
lgbt_r_df.head()

108

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,None,"[27, 53]",876802,en,Saint Drogo,Saint Drogo is a supernatural slowburn themati...,1.810,/ghq9XVBvmlbqrsKA7KDMsYOPjAu.jpg,2022-10-01,Saint Drogo,False,0.0,0
1,False,/Ainzn99TYR1LZWL7pKEBx3AH8Oy.jpg,[35],915164,en,TWO BEERS,"Two lifelong friends, Graham and Adrian, have ...",1.042,/pXEgPcmE1XRwF6543iOFM2XLGzU.jpg,2021-12-10,TWO BEERS,False,10.0,1
2,False,/nsyyWY7F3wjZT6aCkwWIsZXI4wV.jpg,[99],857731,en,Untold: Caitlyn Jenner,Caitlyn Jenner's unlikely path to Olympic glor...,8.015,/gSOXqj8HLTMzdifHOOQnbjgVEVr.jpg,2021-08-24,Untold: Caitlyn Jenner,False,6.5,24
3,False,/zKD0XxAjtK0VYX7j1elDtSNSNbR.jpg,"[18, 12]",552269,en,Joe Bell,"The true story of a small town, working class ...",14.966,/9HfQD60w6f6PPkfdiI6ipJSw0bD.jpg,2021-07-23,Joe Bell,False,6.0,50
4,False,/5C8bfwglg91uZhc2fbfpSjNGamV.jpg,"[27, 9648]",591273,en,Fear Street: 1994,"After a series of brutal slayings, a teen and ...",140.969,/9J9Wy39ZjrVmfk7yMkulpcI5sy0.jpg,2021-06-28,Fear Street: 1994,False,6.8,1375

In [8]:
# Create a variable to hold the list of US ratings names.
ratings = ["NR", "G", "PG", "PG-13", "R", "NC-17"]

In [9]:
# Add a new column in each specific dataframe to label each movie in the dataframe with their corresponding rating
# (this will be important to have later when joining these dataframes into the larger lgbt_movies_df).
lgbt_nr_df["rating"] = ratings[0]
lgbt_g_df["rating"] = ratings[1]
lgbt_pg_df["rating"] = ratings[2]
lgbt_pg13_df["rating"] = ratings[3]
lgbt_r_df["rating"] = ratings[4]
lgbt_nc17_df["rating"] = ratings[5]

In [10]:
# Verify the new column was created correctly.
lgbt_nr_df.head(1)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,rating
0,False,/qQFvUg92Uh1jRXCNgqo9LduBDFD.jpg,[18],920345,en,EMPATHY (Or: The Girl with The Pearled Hair),After running away from her emotionally abusiv...,10.08,/59C1l5dqtKuKuKy5qlE23PV4yC6.jpg,2022-01-25,EMPATHY (Or: The Girl with The Pearled Hair),False,0.0,0,NR

In [11]:
# Verify the new column was created correctly. (Note: there are no films in this dataframe meaning there are no 
# LGBT films with a G rating).
lgbt_g_df.head()

Empty DataFrame
Columns: [rating]
Index: []

In [12]:
# Verify the new column was created correctly.
lgbt_pg_df.head(1)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,rating
0,False,/uIGbye92DBh3PQ645ZnS5gz5PkN.jpg,[18],818367,en,Let's Be Tigers,Avalon’s not ready to process the loss of her ...,11.696,/hPaF9ICdWIAubVAsM9t8elG5ddV.jpg,2021-05-28,Let's Be Tigers,False,7.1,9,PG

In [13]:
# Verify the new column was created correctly.
lgbt_pg13_df.head(1)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,rating
0,False,None,[10749],929477,en,Heart Shot,Teenagers Nikki and Sam are in love and planni...,2.474,None,2022-02-17,Heart Shot,False,0.0,0,PG-13

In [14]:
# Verify the new column was created correctly.
lgbt_r_df.head(1)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,rating
0,False,None,"[27, 53]",876802,en,Saint Drogo,Saint Drogo is a supernatural slowburn themati...,1.81,/ghq9XVBvmlbqrsKA7KDMsYOPjAu.jpg,2022-10-01,Saint Drogo,False,0.0,0,R

In [15]:
# Verify the new column was created correctly.
lgbt_nc17_df.head(1)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,rating
0,False,/m9voXhtc1BM2Opa07co9iNQQHEA.jpg,[35],526034,en,Lez Bomb,A still closeted young woman brings her girlfr...,4.966,/tBiZAkXngPoT80iWxUI9ebSBXli.jpg,2018-11-09,Lez Bomb,False,7.1,35,NC-17

In [16]:
# Drop all columns except for "id" and "rating" from the individual rating dataframes. Column "id" will be needed
# later for joining the dataframes to lgbt_movies_df. (Note: the dataframe for "G" ratings is not included as the 
# dataframe is empty as shown above).
lgbt_nr_df = lgbt_nr_df[["id", "rating"]]
lgbt_pg_df = lgbt_pg_df[["id", "rating"]]
lgbt_pg13_df = lgbt_pg13_df[["id", "rating"]]
lgbt_r_df = lgbt_r_df[["id", "rating"]]
lgbt_nc17_df = lgbt_nc17_df[["id", "rating"]]

In [17]:
# Verify "r" rating dataframe dropped the correct columns.
lgbt_r_df.head()

       id rating
0  876802      R
1  915164      R
2  857731      R
3  552269      R
4  591273      R

In [18]:
# Join the ratings dataframes into the lgbt_movies_df